### ISSUE TITLE
trying orthographic, as perspective projection hits other faces

### ISSUE THREAD

**Issue by juanuys** [marcofugaro/three-projected-material#10]
Hello, thanks for a really awesome library :)

In this screenshot, I'm projecting head-on (i.e. the cubes have no rotation), yet on some cubes you can see the material on the top face (on the bottom half of the cubes, and likewise the underside of the top half of the cubes). I suspect this is because I'm using a `PerspectiveCamera`.

![projection](https://user-images.githubusercontent.com/54897285/98930610-c6171400-24d4-11eb-93d2-98bf125b9406.png)

I see in the example source code that the `OrthographicCamera` is [commented out](https://github.com/marcofugaro/three-projected-material/blob/master/examples/lib/WebGLApp.js#L49). I tried it, but the projection doesn't work that well.

Is `OrthographicCamera` supported? Or is there more to be done?

**Comment by juanuys** [comment]
BTW, my experiment [sources is here](https://github.com/juanuys/perspectives/).

Perspective: https://juanuys.com/perspectives/?c=p
Orthographic: https://juanuys.com/perspectives/?c=o

**Comment by marcofugaro** [comment]
Ugh, [these calculations](https://github.com/marcofugaro/three-projected-material/blob/f88a4aa2f60c5776a50dfba19b1e90d653a1d71d/src/ProjectedMaterial.js#L172-L191) are wrong if the camera is ortographic, I didn't test it with an ortographic camera at all in the end.

I will support Ortographic camera and make an example with it as soon as I can. Your experiment looks really nice btw!

**Comment by juanuys** [comment]
> Ugh

Haha, thank you very much for looking :-)
BTW, I didn't use your module via npm as the GLSL `texture` is now a built-in, so I used [mytexture](https://github.com/juanuys/perspectives/blob/master/lib/ProjectedMaterial.js#L58). Not sure if you want to incorporate that fix too?

**Comment by marcofugaro** [comment]
Thanks for the heads up, I will look into that!

**Comment by juanuys** [comment]
I fixed the aspect ration calculation (see PR), but [still see "smears" on other faces](https://juanuys.com/perspectives/?c=o) when projecting head-on, but not too bothered by that right now, so please feel free to close this issue :-)

**Comment by marcofugaro** [comment]
@juanuys you should be able to fix that by setting `<=` instead of `<` here:

https://github.com/marcofugaro/three-projected-material/blob/f88a4aa2f60c5776a50dfba19b1e90d653a1d71d/src/ProjectedMaterial.js#L137

I'll change that as well, thanks for the PR! I'll merge it this weekend

**Comment by marcofugaro** [comment]
You were right, there were some calculation issues with the OrthographicCamera. Fixed in `v2.0.0` 🥳

I took inspiration from your project for the OrthographicCamera example, hope you don't mind!

https://marcofugaro.github.io/three-projected-material/orthographic-camera

**Comment by juanuys** [comment]
> I took inspiration from your project for the OrthographicCamera example, hope you don't mind!

Not at all :) Happy to assist.
