### ISSUE TITLE
Project multiple textures

### ISSUE THREAD

**Issue by sokhuong-uon** [marcofugaro/three-projected-material#15]
Could we project, multiple materials and multiple textures to a single mesh?

P.S: I don't know where to ask the question so I ask here 😊

**Comment by marcofugaro** [comment]
Yeah it can be done, check out the [Multiple projections](https://marcofugaro.github.io/three-projected-material/multiple-projections) example. 
[I just pass always the same texture here](https://github.com/marcofugaro/three-projected-material/blob/0f9e47f2aebb5d8be8673e2e9b300c5c1bf00ac1/examples/multiple-projections.html#L58-L71), but you can pass multiple textures as well.

**Comment by sokhuong-uon** [comment]
Really nice 😍


![image](https://user-images.githubusercontent.com/77433349/105706889-b7bd8d80-5f44-11eb-8d27-cfd229aeacd5.png)

Appreciate
