### ISSUE TITLE
Project to the front

### ISSUE THREAD

**Issue by sokhuong-uon** [marcofugaro/three-projected-material#16]
How can I project the texture only to the front of the camera?
By default it projects to the front and back of the camera.

![image](https://user-images.githubusercontent.com/77433349/106001938-1de01700-60e3-11eb-90df-fae561ce8e0b.png)

**Comment by marcofugaro** [comment]
@sokhuong-uon weird, could you share a reproducible example?

**Comment by sokhuong-uon** [comment]
here:
https://codesandbox.io/s/red-glitter-470p6?file=/src/components/HelloWorld.vue

**Comment by marcofugaro** [comment]
Fixed in `v2.0.3`!
