### ISSUE TITLE
How to update projection with camera position / rotation?

### ISSUE THREAD

**Issue by notchris** [marcofugaro/three-projected-material#2]
Great library! Wondering how I can update the projection to follow the camera position? Ideally I would never want to see a non-projected face.

**Comment by marcofugaro** [comment]
Hey @notchris thanks! 
You have to the same camera as projector and reference the camera's matrix and position in the material instead of cloning them, here is a quick demo:

https://codesandbox.io/s/projector-demo-48kiz

Closing since it's out of scope of this project
