### ISSUE TITLE
Export model with materials?

### ISSUE THREAD

**Issue by liunuozhi** [marcofugaro/three-projected-material#21]
Hi there! Thank you very much for this very useful implementation.

I would like to export as gltf with materials by [GLTFExporter](https://threejs.org/docs/#examples/en/exporters/GLTFExporter). However, it turns out the materials cannot be shown in output. Is there any way to export the material? Or can be done by any other 3d model format?

**Comment by marcofugaro** [comment]
Hey, unfortunately this is a dynamic material and cannot be exported in a .gltf file as is.
You would need to bake it into a texture, [however three.js does not currently include a baking workflow](https://github.com/mrdoob/three.js/issues/14055) (you would need to code it by yourself).

Alternatively, you can look into recreating the scene in [Blender](https://www.blender.org/), it allows you to bake a lot more stuff and export it as .gltf. 🙂

**Comment by liunuozhi** [comment]
@marcofugaro Thanks for your fast response. It's a pity that it is not available, but still thank you so much for suggestions. I might look at them. Still, thank you so much!

**Comment by marcofugaro** [comment]
No problem!
