### ISSUE TITLE
Project onto a normaly textured mesh

### ISSUE THREAD

**Issue by qwertasyx** [marcofugaro/three-projected-material#26]
Hello,

Is it possible to project a texture onto an already textured mesh? Mixing materials like below results in an error when calling project() -> (Mesh material must be a ProjectedMaterial )

`
const materialA = new MeshBasicMaterial( { map: whateverTexture } )
`
`
const materialB = new ProjectedMaterial( { ... } )
`
`
const mesh = new THREE.Mesh(geometry, [materialA, materialB])
`

so maybe there is another another way that i dont see :)

cheers

**Comment by marcofugaro** [comment]
Fixed in [v2.0.5](https://github.com/marcofugaro/three-projected-material/releases/tag/v2.0.5)
