### ISSUE TITLE
HDRI / image-based / EnvMap-lighting

### ISSUE THREAD

**Issue by patrikHuebner** [marcofugaro/three-projected-material#6]
Great library!

Is there any chance to incorporate image-based / HDRI lighting? As it stands, the material does not react to the _scene.environment_  in THREE.js.

**Comment by marcofugaro** [comment]
`envMap` and other features from [MeshPhysicalMaterial](https://threejs.org/docs/index.html#api/en/materials/MeshPhysicalMaterial) are now available in the material. 🎉

Checkout the envMap lighting example: https://marcofugaro.github.io/three-projected-material/envmap
