### ISSUE TITLE
bake the projection into the mesh

### ISSUE THREAD

**Issue by glyfspace** [marcofugaro/three-projected-material#68]
hey! great library! I am using it to project stable diffusion outputs onto a 3D model. Any ideas on how to bake the projected texture into the mesh? that way I can keep rotating the mesh and fully texture it!

Thanks!

**Comment by marcofugaro** [comment]
> that way I can keep rotating the mesh and fully texture it!

Check out the [multiple projections example](https://marcofugaro.github.io/three-projected-material/multiple-projections.html), is this what you're looking for?

**Comment by glyfspace** [comment]
Yes this is super helpful, but how do I bake the results into the mesh? Thank you!

**Comment by marcofugaro** [comment]
For baking it into a texture, you should look into how to do it with three.js.
By default three.js doesn't offer a way to do it out of the box, you would have to code it yourself. This thread is a good starting point: https://github.com/mrdoob/three.js/issues/14055
