### ISSUE TITLE
update projected texture

### ISSUE THREAD

**Issue by qwertasyx** [marcofugaro/three-projected-material#8]
Hello,

very nice shader :).

With a "Standard" Material we can update a texture with:

`obj.material.map.image.data.set(data, <offset>)`
`obj.material.needsUpdate=true`

Is there a similar way with that shader that i somehow to blind to see? :D

**Comment by qwertasyx** [comment]
just setting 
`obj.material.uniforms.texture.value = newTexture`
kind of solved it for me.

**Comment by marcofugaro** [comment]
In the new version `v2.0.0` you can just set:

```js
obj.material.texture = newTexture
```
